import { readFileSync } from "node:fs";
import { expect, test } from "@playwright/test";

const fixtures = JSON.parse(readFileSync("crates/usage-lens-ui/tests/fixtures.json", "utf8")) as {
  event: { eventId: string; sourceId: string; model: string | null };
};

test("aggregate drilldown opens escaped local message and tool reading with honest quota context", async ({ page }, testInfo) => {
  const errors: string[] = [];
  const external: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  page.on("request", request => { if (new URL(request.url()).origin !== "http://127.0.0.1:4319") external.push(request.url()); });
  await page.goto("/");
  await expect(page).toHaveTitle(/Usage Lens/);
  await expect(page.locator("main")).toContainText("Explore recorded activity");
  await page.locator(".activity-breakdown").getByRole("button", { name: /^User message/ }).click();
  await expect(page.getByLabel("Event type", { exact: true })).toHaveValue("user_prompt");
  await expect(page.getByText("Loading local evidence…", { exact: true })).toHaveCount(0);
  await page.getByLabel("Search retained content", { exact: true }).fill("Synthetic request:");
  await page.getByRole("button", { name: "Apply filters", exact: true }).click();
  await expect(page.locator(".search-scope")).toContainText("Matching retained records: 8");
  const opener = page.getByRole("button", { name: /^View event / }).first();
  await opener.click();
  const dialog = page.getByRole("dialog", { name: "Event detail" });
  await expect(dialog.getByRole("heading", { name: "Message body", exact: true })).toBeVisible();
  await expect(dialog.locator(".reader-section .content-body")).toContainText("Synthetic request:");
  await expect(dialog).toContainText("Actual remote-send evidence unavailable");
  await expect(dialog).toContainText("Unknown · not recorded");
  await expect(dialog.getByRole("button", { name: "Close event detail" })).toBeFocused();
  await page.keyboard.press("Escape");
  await expect(dialog).toHaveCount(0);
  await expect(opener).toBeFocused();
  await opener.click();
  await page.getByRole("button", { name: "Close event detail" }).click();
  await expect(dialog).toHaveCount(0);
  await page.getByRole("button", { name: "Reset", exact: true }).click();
  await expect(page.getByText("Loading local evidence…", { exact: true })).toHaveCount(0);
  await page.getByLabel("Event type", { exact: true }).selectOption("tool_call");
  await page.getByRole("button", { name: "Apply filters", exact: true }).click();
  await page.getByRole("button", { name: "View event demo-event-8", exact: true }).click();
  await expect(dialog.getByRole("heading", { name: "Tool arguments", exact: true })).toBeVisible();
  await expect(dialog.getByRole("heading", { name: "Tool result", exact: true })).toBeVisible();
  await dialog.locator(".retained-file summary").click();
  await expect(dialog).toContainText("date,tokens");
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath("local-tool-reader-en.png"), fullPage: false });
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: "View event demo-event-6", exact: true }).click();
  await expect(dialog).toContainText("Content unavailable");
  await expect(dialog.locator(".content-body")).toHaveCount(0);
  await page.keyboard.press("Escape");
  const nav = page.getByRole("navigation", { name: "Main navigation" });
  await nav.getByRole("button", { name: "Quotas", exact: true }).click();
  await expect(page.locator(".quota-panel").first()).toContainText("Reported weekly window");
  await expect(page.locator(".token-period")).toContainText("Token period not selected or unavailable");
  await expect(page.getByText("Loading local evidence…", { exact: true })).toHaveCount(0);
  await page.getByLabel("Token period from (UTC)", { exact: true }).fill("2026-10-01");
  await page.getByLabel("Token period to (UTC)", { exact: true }).fill("2026-10-03");
  await page.getByRole("button", { name: "Read token period", exact: true }).click();
  await expect(page.locator(".token-period .response-count")).toContainText("0");
  await expect(page.locator(".token-period")).toContainText("Not recorded for these response tokens");
  await expect(page.locator(".token-period")).toContainText("no retained dated evidence");
  await page.getByLabel("Token period to (UTC)", { exact: true }).fill("2026-09-01");
  await page.getByRole("button", { name: "Read token period", exact: true }).click();
  await expect(page.locator(".token-period .response-count")).toHaveCount(0);
  await page.locator(".token-period").getByRole("button", { name: "Retry", exact: true }).click();
  await expect(page.locator(".token-period")).toContainText("invalid_token_period");
  await expect(page.locator(".token-period .response-count")).toHaveCount(0);
  await page.getByLabel("Token period to (UTC)", { exact: true }).fill("2026-10-03");
  await page.locator(".token-period").getByRole("button", { name: "Retry", exact: true }).click();
  await expect(page.locator(".token-period .response-count")).toContainText("0");
  await page.getByLabel("Language", { exact: true }).selectOption("zh");
  await page.getByRole("button", { name: "使用深色主题", exact: true }).click();
  await expect(page.locator(".token-period")).toContainText("这些响应 Token 未记录此信息");
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath("token-period-zh-dark.png"), fullPage: true });
  await page.getByRole("navigation", { name: "主导航" }).getByRole("button", { name: "活动", exact: true }).click();
  await expect(page.getByLabel("事件类型", { exact: true })).toHaveValue("tool_call");
  expect(errors).toEqual([]);
  expect(external).toEqual([]);
});

test("search pagination stays on the submitted query and discarded requests cannot replace newer navigation", async ({ page }) => {
  const queries: string[] = [];
  let staleRequested = false;
  let releaseStale: (() => void) | undefined;
  const staleBarrier = new Promise<void>(resolve => { releaseStale = resolve; });
  await page.route(/\/api\/events\/search\?/, async route => {
    const url = new URL(route.request().url());
    const query = url.searchParams.get("query") ?? "";
    queries.push(query);
    if (query === "slow") {
      staleRequested = true;
      await staleBarrier;
    }
    const second = url.searchParams.has("cursor");
    await route.fulfill({ json: { source: { id: "demo" }, events: [{ ...fixtures.event, eventId: query === "slow" ? "stale-search" : second ? "second-search" : "first-search" }], nextCursor: second ? null : "cursor-v1", search: { searchedRecordCount: "10000", matchedCount: "2", truncated: true } } }).catch(() => {});
  });
  await page.goto("/");
  await page.getByRole("navigation").getByRole("button", { name: "Activity", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Recorded activity", exact: true })).toBeVisible();
  await expect(page.getByText("Loading local evidence…", { exact: true })).toHaveCount(0);
  await page.getByLabel("Search retained content", { exact: true }).fill("submitted");
  await page.getByRole("button", { name: "Apply filters", exact: true }).click();
  await expect(page.getByRole("button", { name: "View event first-search" })).toBeVisible();
  await expect(page.locator(".search-scope")).toContainText("Older retained content is outside this search window");
  await page.getByLabel("Search retained content", { exact: true }).fill("unsubmitted draft");
  await page.getByRole("button", { name: "Load more records", exact: true }).click();
  await expect(page.getByRole("button", { name: "View event second-search" })).toBeVisible();
  expect(queries).toEqual(["submitted", "submitted"]);
  await expect(page.getByLabel("Search retained content", { exact: true })).toHaveValue("unsubmitted draft");
  await page.getByLabel("Search retained content", { exact: true }).fill("slow");
  await page.getByRole("button", { name: "Apply filters", exact: true }).click();
  await expect.poll(() => staleRequested).toBe(true);
  await page.getByRole("button", { name: "Reset", exact: true }).click();
  releaseStale?.();
  await expect(page.getByRole("button", { name: /^View event demo-event-/ }).first()).toBeVisible();
  await expect(page.getByRole("button", { name: "View event stale-search" })).toHaveCount(0);
  await expect(page.locator(".search-scope")).toHaveCount(0);
  await page.getByLabel("From", { exact: true }).fill("2026-10-03");
  await page.getByLabel("To", { exact: true }).fill("2026-10-01");
  await page.getByRole("button", { name: "Apply filters", exact: true }).click();
  await page.getByRole("button", { name: "Retry", exact: true }).click();
  await expect(page.getByRole("button", { name: /^View event / })).toHaveCount(0);
  await expect(page.getByRole("alert")).toContainText("invalid_date_range");
  await page.getByRole("navigation").getByRole("button", { name: "Overview", exact: true }).click();
  await expect(page.getByRole("heading", { level: 1, name: "Your usage, in focus" })).toBeVisible();
});
